---
- name: Install psycopg2
  hosts: all
  become: true
  tasks: 
    - name: Install PostgreSQL development packages
      yum:
        name:
          - postgresql-devel
        state: present
      become: true
      
    - name: Install pip
      yum:
        name:
          - python3-pip
        state: present
      become: true

    - name: Install psycopg2 package via pip
      pip:
        name: psycopg2
        state: present
        executable: pip3
      become: true
